:global:
  componentName: appcat-service-postgresql
  githubUrl: https://github.com/ZuGao/component-appcat-service-postgresql
  feature_goldenTests: true

docs/antora.yml:
  name: appcat-service-postgresql
  title: appcat-service-postgresql
.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
