:global:
  componentName: appcat-service-postgresql
  githubUrl: https://github.com/projectsyn/component-appcat-service-postgresql
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
